### ISSUE TITLE
Working with Pushstate

### ISSUE THREAD

**Issue by mzafer** [tough-griff/redux-react-router-todomvc#3]
Hi There,

How to make this example work with pushstate. The app works only if I use http://localhost:8080/ but using any other path like http://localhost:8080/todos/all, http://localhost:8080/todos/active returns

Cannot GET /todos/active

Thanks
Zafer

**Comment by tough-griff** [comment]
I never encountered this problem, but I have updated the `react-router` package since you opened up this issue, which seems like a likely candidate for the cause of your bug.
