### ISSUE TITLE
App crashing on startup.

### ISSUE THREAD

**Issue by thehashrocket** [tough-griff/redux-react-router-todomvc#4]
I downloaded the app, ran npm install, and then npm start and it crashed immediately. 

Here's the screenshot and i'm attaching the log as well.

<img width="1044" alt="terminal_ _-bash_ _147x52_and_redux-react-router-todomvc_and_welcome_to_webstorm" src="https://cloud.githubusercontent.com/assets/342353/12433727/fefabc34-bebf-11e5-9ade-74a31f389f3c.png">

[npm-debug.log.zip](https://github.com/tough-griff/redux-react-router-todomvc/files/96645/npm-debug.log.zip)

**Comment by tough-griff** [comment]
I was unable to reproduce any error after clearing my node_modules directory and installing from scratch.

I've been managing dependencies with npm 3, so there may be an incompatibility with npm 2.
